language: python
python:
  - "2.7"
  - "pypy"

before_script: cd ksweb

install:
  - "pip install -e ksweb[testing]"
  - "pip install coveralls"
  - "pip install codecov"

script:
  - "nosetests -v --with-coverage"

after_success:
  - coveralls
  - codecov
