language: python
python:
  - "2.7"
  - "pypy"

before_script: cd ksweb

install:
  - "pip install nose"
  - "pip install coveralls"
  - "pip install codecov"
  - "pip install --no-use-wheel -e ksweb[testing]"

script:
  - "nosetests -v --with-coverage"

after_success:
  - coveralls
  - codecov
